//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5420 版自动生成。
// 
namespace HPDA {
    using System;
    using System.Data;
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ProDataSet")]
    public partial class ProDataSet : global::System.Data.DataSet {
        
        private ProDeliveryDataTable tableProDelivery;
        
        private ProDeliveryDetailDataTable tableProDeliveryDetail;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProDeliveryDataTable ProDelivery {
            get {
                return this.tableProDelivery;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProDeliveryDetailDataTable ProDeliveryDetail {
            get {
                return this.tableProDeliveryDetail;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            ProDataSet cln = ((ProDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["ProDelivery"] != null)) {
                    base.Tables.Add(new ProDeliveryDataTable(ds.Tables["ProDelivery"]));
                }
                if ((ds.Tables["ProDeliveryDetail"] != null)) {
                    base.Tables.Add(new ProDeliveryDetailDataTable(ds.Tables["ProDeliveryDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableProDelivery = ((ProDeliveryDataTable)(base.Tables["ProDelivery"]));
            if ((initTable == true)) {
                if ((this.tableProDelivery != null)) {
                    this.tableProDelivery.InitVars();
                }
            }
            this.tableProDeliveryDetail = ((ProDeliveryDetailDataTable)(base.Tables["ProDeliveryDetail"]));
            if ((initTable == true)) {
                if ((this.tableProDeliveryDetail != null)) {
                    this.tableProDeliveryDetail.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "ProDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ProDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableProDelivery = new ProDeliveryDataTable();
            base.Tables.Add(this.tableProDelivery);
            this.tableProDeliveryDetail = new ProDeliveryDetailDataTable();
            base.Tables.Add(this.tableProDeliveryDetail);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeProDelivery() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeProDeliveryDetail() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ProDataSet ds = new ProDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void ProDeliveryRowChangeEventHandler(object sender, ProDeliveryRowChangeEvent e);
        
        public delegate void ProDeliveryDetailRowChangeEventHandler(object sender, ProDeliveryDetailRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ProDeliveryDataTable : global::System.Data.TypedTableBase<ProDeliveryRow> {
            
            private global::System.Data.DataColumn columnRowNo;
            
            private global::System.Data.DataColumn columncOrderNumber;
            
            private global::System.Data.DataColumn columncCusCode;
            
            private global::System.Data.DataColumn columncCusName;
            
            private global::System.Data.DataColumn columncMaker;
            
            private global::System.Data.DataColumn columndMaketime;
            
            private global::System.Data.DataColumn columncDepCode;
            
            private global::System.Data.DataColumn columncDepName;
            
            private global::System.Data.DataColumn columncMemo;
            
            private global::System.Data.DataColumn columncVerifyState;
            
            private global::System.Data.DataColumn columncHandler;
            
            private global::System.Data.DataColumn columndVeriDate;
            
            private global::System.Data.DataColumn columnAutoID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryDataTable() {
                this.TableName = "ProDelivery";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ProDeliveryDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RowNoColumn {
                get {
                    return this.columnRowNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cOrderNumberColumn {
                get {
                    return this.columncOrderNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cCusCodeColumn {
                get {
                    return this.columncCusCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cCusNameColumn {
                get {
                    return this.columncCusName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cMakerColumn {
                get {
                    return this.columncMaker;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn dMaketimeColumn {
                get {
                    return this.columndMaketime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cDepCodeColumn {
                get {
                    return this.columncDepCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cDepNameColumn {
                get {
                    return this.columncDepName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cMemoColumn {
                get {
                    return this.columncMemo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cVerifyStateColumn {
                get {
                    return this.columncVerifyState;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cHandlerColumn {
                get {
                    return this.columncHandler;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn dVeriDateColumn {
                get {
                    return this.columndVeriDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AutoIDColumn {
                get {
                    return this.columnAutoID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryRow this[int index] {
                get {
                    return ((ProDeliveryRow)(this.Rows[index]));
                }
            }
            
            public event ProDeliveryRowChangeEventHandler ProDeliveryRowChanging;
            
            public event ProDeliveryRowChangeEventHandler ProDeliveryRowChanged;
            
            public event ProDeliveryRowChangeEventHandler ProDeliveryRowDeleting;
            
            public event ProDeliveryRowChangeEventHandler ProDeliveryRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddProDeliveryRow(ProDeliveryRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryRow AddProDeliveryRow(string cOrderNumber, string cCusCode, string cCusName, string cMaker, string dMaketime, string cDepCode, string cDepName, string cMemo, string cVerifyState, string cHandler, string dVeriDate, string AutoID) {
                ProDeliveryRow rowProDeliveryRow = ((ProDeliveryRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        cOrderNumber,
                        cCusCode,
                        cCusName,
                        cMaker,
                        dMaketime,
                        cDepCode,
                        cDepName,
                        cMemo,
                        cVerifyState,
                        cHandler,
                        dVeriDate,
                        AutoID};
                rowProDeliveryRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowProDeliveryRow);
                return rowProDeliveryRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                ProDeliveryDataTable cln = ((ProDeliveryDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new ProDeliveryDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnRowNo = base.Columns["RowNo"];
                this.columncOrderNumber = base.Columns["cOrderNumber"];
                this.columncCusCode = base.Columns["cCusCode"];
                this.columncCusName = base.Columns["cCusName"];
                this.columncMaker = base.Columns["cMaker"];
                this.columndMaketime = base.Columns["dMaketime"];
                this.columncDepCode = base.Columns["cDepCode"];
                this.columncDepName = base.Columns["cDepName"];
                this.columncMemo = base.Columns["cMemo"];
                this.columncVerifyState = base.Columns["cVerifyState"];
                this.columncHandler = base.Columns["cHandler"];
                this.columndVeriDate = base.Columns["dVeriDate"];
                this.columnAutoID = base.Columns["AutoID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnRowNo = new global::System.Data.DataColumn("RowNo", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRowNo);
                this.columncOrderNumber = new global::System.Data.DataColumn("cOrderNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncOrderNumber);
                this.columncCusCode = new global::System.Data.DataColumn("cCusCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncCusCode);
                this.columncCusName = new global::System.Data.DataColumn("cCusName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncCusName);
                this.columncMaker = new global::System.Data.DataColumn("cMaker", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncMaker);
                this.columndMaketime = new global::System.Data.DataColumn("dMaketime", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndMaketime);
                this.columncDepCode = new global::System.Data.DataColumn("cDepCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncDepCode);
                this.columncDepName = new global::System.Data.DataColumn("cDepName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncDepName);
                this.columncMemo = new global::System.Data.DataColumn("cMemo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncMemo);
                this.columncVerifyState = new global::System.Data.DataColumn("cVerifyState", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncVerifyState);
                this.columncHandler = new global::System.Data.DataColumn("cHandler", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncHandler);
                this.columndVeriDate = new global::System.Data.DataColumn("dVeriDate", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndVeriDate);
                this.columnAutoID = new global::System.Data.DataColumn("AutoID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAutoID);
                this.columnRowNo.AutoIncrement = true;
                this.columnRowNo.AutoIncrementSeed = 1;
                this.columncCusCode.Caption = "FItemID";
                this.columncCusName.Caption = "FEntryID";
                this.columncMaker.Caption = "cInvCode";
                this.columncDepCode.Caption = "cInvName";
                this.columncDepName.Caption = "cUnit";
                this.columncMemo.Caption = "cCusAddress";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryRow NewProDeliveryRow() {
                return ((ProDeliveryRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ProDeliveryRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(ProDeliveryRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ProDeliveryRowChanged != null)) {
                    this.ProDeliveryRowChanged(this, new ProDeliveryRowChangeEvent(((ProDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ProDeliveryRowChanging != null)) {
                    this.ProDeliveryRowChanging(this, new ProDeliveryRowChangeEvent(((ProDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ProDeliveryRowDeleted != null)) {
                    this.ProDeliveryRowDeleted(this, new ProDeliveryRowChangeEvent(((ProDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ProDeliveryRowDeleting != null)) {
                    this.ProDeliveryRowDeleting(this, new ProDeliveryRowChangeEvent(((ProDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveProDeliveryRow(ProDeliveryRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ProDataSet ds = new ProDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ProDeliveryDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ProDeliveryDetailDataTable : global::System.Data.TypedTableBase<ProDeliveryDetailRow> {
            
            private global::System.Data.DataColumn columnDataColumn1;
            
            private global::System.Data.DataColumn columnDataColumn2;
            
            private global::System.Data.DataColumn columna;
            
            private global::System.Data.DataColumn columnDataColumn3;
            
            private global::System.Data.DataColumn columnDataColumn4;
            
            private global::System.Data.DataColumn columnDataColumn5;
            
            private global::System.Data.DataColumn columnDataColumn6;
            
            private global::System.Data.DataColumn columnDataColumn7;
            
            private global::System.Data.DataColumn columnDataColumn8;
            
            private global::System.Data.DataColumn columnDataColumn9;
            
            private global::System.Data.DataColumn columnDataColumn10;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryDetailDataTable() {
                this.TableName = "ProDeliveryDetail";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ProDeliveryDetailDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn1Column {
                get {
                    return this.columnDataColumn1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn2Column {
                get {
                    return this.columnDataColumn2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn aColumn {
                get {
                    return this.columna;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn3Column {
                get {
                    return this.columnDataColumn3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn4Column {
                get {
                    return this.columnDataColumn4;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn5Column {
                get {
                    return this.columnDataColumn5;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn6Column {
                get {
                    return this.columnDataColumn6;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn7Column {
                get {
                    return this.columnDataColumn7;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn8Column {
                get {
                    return this.columnDataColumn8;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn9Column {
                get {
                    return this.columnDataColumn9;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataColumn10Column {
                get {
                    return this.columnDataColumn10;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryDetailRow this[int index] {
                get {
                    return ((ProDeliveryDetailRow)(this.Rows[index]));
                }
            }
            
            public event ProDeliveryDetailRowChangeEventHandler ProDeliveryDetailRowChanging;
            
            public event ProDeliveryDetailRowChangeEventHandler ProDeliveryDetailRowChanged;
            
            public event ProDeliveryDetailRowChangeEventHandler ProDeliveryDetailRowDeleting;
            
            public event ProDeliveryDetailRowChangeEventHandler ProDeliveryDetailRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddProDeliveryDetailRow(ProDeliveryDetailRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryDetailRow AddProDeliveryDetailRow(string DataColumn1, string DataColumn2, string a, string DataColumn3, string DataColumn4, string DataColumn5, string DataColumn6, string DataColumn7, string DataColumn8, string DataColumn9, string DataColumn10) {
                ProDeliveryDetailRow rowProDeliveryDetailRow = ((ProDeliveryDetailRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        DataColumn1,
                        DataColumn2,
                        a,
                        DataColumn3,
                        DataColumn4,
                        DataColumn5,
                        DataColumn6,
                        DataColumn7,
                        DataColumn8,
                        DataColumn9,
                        DataColumn10};
                rowProDeliveryDetailRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowProDeliveryDetailRow);
                return rowProDeliveryDetailRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                ProDeliveryDetailDataTable cln = ((ProDeliveryDetailDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new ProDeliveryDetailDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnDataColumn1 = base.Columns["DataColumn1"];
                this.columnDataColumn2 = base.Columns["DataColumn2"];
                this.columna = base.Columns["a"];
                this.columnDataColumn3 = base.Columns["DataColumn3"];
                this.columnDataColumn4 = base.Columns["DataColumn4"];
                this.columnDataColumn5 = base.Columns["DataColumn5"];
                this.columnDataColumn6 = base.Columns["DataColumn6"];
                this.columnDataColumn7 = base.Columns["DataColumn7"];
                this.columnDataColumn8 = base.Columns["DataColumn8"];
                this.columnDataColumn9 = base.Columns["DataColumn9"];
                this.columnDataColumn10 = base.Columns["DataColumn10"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnDataColumn1 = new global::System.Data.DataColumn("DataColumn1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn1);
                this.columnDataColumn2 = new global::System.Data.DataColumn("DataColumn2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn2);
                this.columna = new global::System.Data.DataColumn("a", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columna);
                this.columnDataColumn3 = new global::System.Data.DataColumn("DataColumn3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn3);
                this.columnDataColumn4 = new global::System.Data.DataColumn("DataColumn4", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn4);
                this.columnDataColumn5 = new global::System.Data.DataColumn("DataColumn5", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn5);
                this.columnDataColumn6 = new global::System.Data.DataColumn("DataColumn6", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn6);
                this.columnDataColumn7 = new global::System.Data.DataColumn("DataColumn7", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn7);
                this.columnDataColumn8 = new global::System.Data.DataColumn("DataColumn8", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn8);
                this.columnDataColumn9 = new global::System.Data.DataColumn("DataColumn9", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn9);
                this.columnDataColumn10 = new global::System.Data.DataColumn("DataColumn10", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataColumn10);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryDetailRow NewProDeliveryDetailRow() {
                return ((ProDeliveryDetailRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ProDeliveryDetailRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(ProDeliveryDetailRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ProDeliveryDetailRowChanged != null)) {
                    this.ProDeliveryDetailRowChanged(this, new ProDeliveryDetailRowChangeEvent(((ProDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ProDeliveryDetailRowChanging != null)) {
                    this.ProDeliveryDetailRowChanging(this, new ProDeliveryDetailRowChangeEvent(((ProDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ProDeliveryDetailRowDeleted != null)) {
                    this.ProDeliveryDetailRowDeleted(this, new ProDeliveryDetailRowChangeEvent(((ProDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ProDeliveryDetailRowDeleting != null)) {
                    this.ProDeliveryDetailRowDeleting(this, new ProDeliveryDetailRowChangeEvent(((ProDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveProDeliveryDetailRow(ProDeliveryDetailRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ProDataSet ds = new ProDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ProDeliveryDetailDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ProDeliveryRow : global::System.Data.DataRow {
            
            private ProDeliveryDataTable tableProDelivery;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ProDeliveryRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableProDelivery = ((ProDeliveryDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int RowNo {
                get {
                    try {
                        return ((int)(this[this.tableProDelivery.RowNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“RowNo”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.RowNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cOrderNumber {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cOrderNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cOrderNumber”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cOrderNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cCusCode {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cCusCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cCusCode”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cCusCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cCusName {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cCusNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cCusName”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cCusNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cMaker {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cMakerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cMaker”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cMakerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string dMaketime {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.dMaketimeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“dMaketime”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.dMaketimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cDepCode {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cDepCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cDepCode”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cDepCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cDepName {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cDepNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cDepName”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cDepNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cMemo {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cMemoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cMemo”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cMemoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cVerifyState {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cVerifyStateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cVerifyState”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cVerifyStateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cHandler {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.cHandlerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“cHandler”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.cHandlerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string dVeriDate {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.dVeriDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“dVeriDate”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.dVeriDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AutoID {
                get {
                    try {
                        return ((string)(this[this.tableProDelivery.AutoIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDelivery”中列“AutoID”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDelivery.AutoIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRowNoNull() {
                return this.IsNull(this.tableProDelivery.RowNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRowNoNull() {
                this[this.tableProDelivery.RowNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscOrderNumberNull() {
                return this.IsNull(this.tableProDelivery.cOrderNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcOrderNumberNull() {
                this[this.tableProDelivery.cOrderNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscCusCodeNull() {
                return this.IsNull(this.tableProDelivery.cCusCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcCusCodeNull() {
                this[this.tableProDelivery.cCusCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscCusNameNull() {
                return this.IsNull(this.tableProDelivery.cCusNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcCusNameNull() {
                this[this.tableProDelivery.cCusNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscMakerNull() {
                return this.IsNull(this.tableProDelivery.cMakerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcMakerNull() {
                this[this.tableProDelivery.cMakerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsdMaketimeNull() {
                return this.IsNull(this.tableProDelivery.dMaketimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetdMaketimeNull() {
                this[this.tableProDelivery.dMaketimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscDepCodeNull() {
                return this.IsNull(this.tableProDelivery.cDepCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcDepCodeNull() {
                this[this.tableProDelivery.cDepCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscDepNameNull() {
                return this.IsNull(this.tableProDelivery.cDepNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcDepNameNull() {
                this[this.tableProDelivery.cDepNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscMemoNull() {
                return this.IsNull(this.tableProDelivery.cMemoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcMemoNull() {
                this[this.tableProDelivery.cMemoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscVerifyStateNull() {
                return this.IsNull(this.tableProDelivery.cVerifyStateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcVerifyStateNull() {
                this[this.tableProDelivery.cVerifyStateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscHandlerNull() {
                return this.IsNull(this.tableProDelivery.cHandlerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcHandlerNull() {
                this[this.tableProDelivery.cHandlerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsdVeriDateNull() {
                return this.IsNull(this.tableProDelivery.dVeriDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetdVeriDateNull() {
                this[this.tableProDelivery.dVeriDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAutoIDNull() {
                return this.IsNull(this.tableProDelivery.AutoIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAutoIDNull() {
                this[this.tableProDelivery.AutoIDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ProDeliveryDetailRow : global::System.Data.DataRow {
            
            private ProDeliveryDetailDataTable tableProDeliveryDetail;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ProDeliveryDetailRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableProDeliveryDetail = ((ProDeliveryDetailDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn1 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn1”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn2 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn2”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string a {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.aColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“a”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.aColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn3 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn3”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn4 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn4Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn4”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn4Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn5 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn5Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn5”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn5Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn6 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn6Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn6”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn6Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn7 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn7Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn7”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn7Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn8 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn8Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn8”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn8Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn9 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn9Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn9”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn9Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataColumn10 {
                get {
                    try {
                        return ((string)(this[this.tableProDeliveryDetail.DataColumn10Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“ProDeliveryDetail”中列“DataColumn10”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableProDeliveryDetail.DataColumn10Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn1Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn1Null() {
                this[this.tableProDeliveryDetail.DataColumn1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn2Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn2Null() {
                this[this.tableProDeliveryDetail.DataColumn2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsaNull() {
                return this.IsNull(this.tableProDeliveryDetail.aColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetaNull() {
                this[this.tableProDeliveryDetail.aColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn3Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn3Null() {
                this[this.tableProDeliveryDetail.DataColumn3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn4Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn4Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn4Null() {
                this[this.tableProDeliveryDetail.DataColumn4Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn5Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn5Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn5Null() {
                this[this.tableProDeliveryDetail.DataColumn5Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn6Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn6Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn6Null() {
                this[this.tableProDeliveryDetail.DataColumn6Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn7Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn7Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn7Null() {
                this[this.tableProDeliveryDetail.DataColumn7Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn8Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn8Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn8Null() {
                this[this.tableProDeliveryDetail.DataColumn8Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn9Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn9Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn9Null() {
                this[this.tableProDeliveryDetail.DataColumn9Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataColumn10Null() {
                return this.IsNull(this.tableProDeliveryDetail.DataColumn10Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataColumn10Null() {
                this[this.tableProDeliveryDetail.DataColumn10Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        public class ProDeliveryRowChangeEvent : global::System.EventArgs {
            
            private ProDeliveryRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryRowChangeEvent(ProDeliveryRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        public class ProDeliveryDetailRowChangeEvent : global::System.EventArgs {
            
            private ProDeliveryDetailRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryDetailRowChangeEvent(ProDeliveryDetailRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ProDeliveryDetailRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace ProDataSetUtil {
    using System;
    using System.Data;
    
    
    public partial class DesignerUtil {
        
        public static bool IsDesignTime() {
            // Determine if this instance is running against .NET Framework by using the MSCoreLib PublicKeyToken
            System.Reflection.Assembly mscorlibAssembly = typeof(int).Assembly;
            if ((mscorlibAssembly != null)) {
                if (mscorlibAssembly.FullName.ToUpper().EndsWith("B77A5C561934E089")) {
                    return true;
                }
            }
            return false;
        }
        
        public static bool IsRunTime() {
            // Determine if this instance is running against .NET Compact Framework by using the MSCoreLib PublicKeyToken
            System.Reflection.Assembly mscorlibAssembly = typeof(int).Assembly;
            if ((mscorlibAssembly != null)) {
                if (mscorlibAssembly.FullName.ToUpper().EndsWith("969DB8053D3322AC")) {
                    return true;
                }
            }
            return false;
        }
    }
}
